name: Generate NVDA Returns Excel

on:
  workflow_dispatch:
  push:
    paths:
      - 'data/nvda_us_m.csv'
      - 'scripts/generate_nvda_returns_excel.py'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy xlsxwriter

      - name: Generate Excel report
        run: |
          python scripts/generate_nvda_returns_excel.py

      - name: Commit Excel report
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Generate NVDA_Returns_Analysis.xlsx'
          file_pattern: 'reports/NVDA_Returns_Analysis.xlsx'
